services:
  chargecaster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chargecaster
    read_only: true
    ports:
      - "6969:8080"
    environment:
      CHARGECASTER_CONFIG: /app/config.yaml
    volumes:
      - ./data:/data
      - ${CHARGECASTER_CONFIG_FILE:-./config.local.yaml}:/app/config.yaml:ro
    restart: unless-stopped
